# Generated by Django 4.0.1 on 2022-01-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_rename_metric_time_sensorreadings_date'), ('core', '0003_alter_sensorreadings_options_and_more'), ('core', '0004_farmreport_ph_rainfall_temperature_and_more'), ('core', '0005_farm'), ('core', '0006_alter_farm_options_alter_farmreport_farm'), ('core', '0007_alter_ph_farm_report_alter_temperature_farm_report'), ('core', '0008_alter_ph_farm_report_alter_rainfall_farm_report_and_more'), ('core', '0009_alter_rainfall_options'), ('core', '0010_alter_ph_farm_report_alter_rainfall_farm_report_and_more'), ('core', '0011_alter_temperature_farm_report'), ('core', '0012_alter_ph_farm_report_alter_rainfall_farm_report_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.PositiveSmallIntegerField(choices=[(0, "Noora's farm"), (1, 'Friman Metsola collective'), (2, "Organic Ossi's Impact That Lasts plantation"), (3, 'PartialTech Research Farm')])),
                ('date', models.DateTimeField()),
                ('time_reported', models.BooleanField(default=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rainfall', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='sensorreadings',
            constraint=models.UniqueConstraint(fields=('farm', 'date'), name='unified readings'),
        ),
        migrations.CreateModel(
            name='FarmReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.PositiveSmallIntegerField(choices=[(0, "Noora's farm"), (1, 'Friman Metsola collective'), (2, "Organic Ossi's Impact That Lasts plantation"), (3, 'PartialTech Research Farm')])),
                ('date', models.DateTimeField()),
                ('time_reported', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('farm_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmreport')),
            ],
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall', models.DecimalField(decimal_places=1, max_digits=4)),
                ('farm_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmreport')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('farm_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmreport')),
            ],
        ),
        migrations.DeleteModel(
            name='SensorReadings',
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('input_file', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='farmreport',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farm'),
        ),
        migrations.AlterField(
            model_name='ph',
            name='farm_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ph', to='core.farmreport'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='farm_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='core.farmreport'),
        ),
        migrations.AlterField(
            model_name='ph',
            name='farm_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.farmreport'),
        ),
        migrations.AlterField(
            model_name='rainfall',
            name='farm_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='rainfall', to='core.farmreport'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='farm_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.farmreport'),
        ),
        migrations.AlterModelOptions(
            name='rainfall',
            options={'verbose_name': 'Rainfall'},
        ),
        migrations.AlterField(
            model_name='ph',
            name='farm_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmreport'),
        ),
        migrations.AlterField(
            model_name='rainfall',
            name='farm_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='rainfall', to='core.farmreport'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='farm_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmreport'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='farm_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='core.farmreport'),
        ),
        migrations.AlterField(
            model_name='ph',
            name='farm_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ph', to='core.farmreport'),
        ),
        migrations.AlterField(
            model_name='rainfall',
            name='farm_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall', to='core.farmreport'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='farm_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='core.farmreport'),
        ),
    ]
